### ISSUE TITLE
What are these numbers?

### ISSUE THREAD

**Issue by Raffaele74** [carat-project/carat-android#10]
I recommended using Carat to several people with moderately positive returns.
Often I received a wrong number interpretation.

In particular:
> A lot of people think that C = f (A) and they surprised to see D.
> Many people have noticed that D are minutes and B are seconds. It seems inconsistent with them.

> First. I do not judge how they think this and how many do it, but if we think we do something, how many digits can we use? (I think, for example, "Battery full charge life" - italian 44 or more digit)
> Second. If I propose to Github to replace "Error" (B) with "Medium-Value Error" is correct?

People say Carat's battery life was cautious enough.
When C> 10h, people tell me they need only one charge a day (so about 16 hours)
When C> 9h people say they need to recharge before dinner (so about 12 hours)
What do you think about a calibration campaign using the Carat Questionary Tool?

![screenshot_2017-05-25-09-11-23](https://cloud.githubusercontent.com/assets/24221053/26445489/af020fb6-4140-11e7-8546-bd941a4cd950.png)

**Comment by lagerspetz** [comment]
This has been updated now. Carat now includes only the last year's data, not all data ever, for each user. This means numbers will reflect your current battery life better.
