### ISSUE TITLE
Italian translation corrections

### ISSUE THREAD

**Issue by SteX986** [carat-project/carat-android#14]
Hi, i have a suggestion for a couple of small italian translation problems. I'm attaching screenshots too!

-During the data update, the text string is too long and ends under the share button!
Suggestion: change "Aggiornamento il mio dispositivo" (updating THE my device, also very rarely used) in "Aggiornamento dispositivo" (updating device)
https://www.dropbox.com/s/iqrzcyxzav4nk73/Carat1.png?dl=0

-During the data update, "inviando i campioni" it's the literal translation of  (i am) "sending the samples", but usually all apps and pc software uses a slightly different composition, the impersonal form, which is "invio dei campioni". It has the same mean, but it has no phrase subject
https://www.dropbox.com/s/0y8o4t17e2bezi5/Carat2.png?dl=0

-In the hogs section, "usually" has been translated in "usualmente", but this form was used in novels only until the 19th century. The correct translation on the actual language is "abitualmente"
https://www.dropbox.com/s/pwykjg70g7svt91/Carat3.png?dl=0

-The last one is a wrong accent, in "Aggiornato [number] minuti fà" (update [number] minute[s] ago). 
The right word is "fa", without the accent!
https://www.dropbox.com/s/5eg54tzxoi8gnfk/Carat4.png?dl=0

I also would thank you for the translation, you did a very good work in all the other strings!

**Comment by lagerspetz** [comment]
Thank you, I will make sure these go to the next version.

**Comment by lagerspetz** [comment]
There is a small issue with the first one. As "Il mio dispositivo" is "my device" in the Carat app, and we just add "Aggiornamento" in front of it when updating, changing this would also change the name of "My Device" in italian. Do you have a suggestion for that?
Otherwise the only possible fix will be to add different translations to what the screens are called and what is shown when updating them, which will mean more work for us and the next person who contributes translations.

**Comment by Raffaele74** [comment]
We can change "Aggiornamento" with "Aggiorno" and "Il mio" with "Questo". In English "Upgrading" with  "I'm upgrading" and "My" with "These".  Whta do you think about?

**Comment by lagerspetz** [comment]
Looks like "Questo" is longer than "Il mio". Also this will change the title of "My Device" screen to "Questo Dispositivo". Is that ok?

**Comment by Raffaele74** [comment]
No. It is longer in English, but it is shorter in Italian.
In my opinion "Aggiorno Il mio dispositivo" (-5) is a beautifull solution (also if it is not perfect in Italian).

![carat](https://user-images.githubusercontent.com/24221053/27374026-a57d89cc-566a-11e7-8842-4c59ac2e196b.png)

**Comment by SteX986** [comment]
"Aggiorno il mio dispositivo" and "Aggiorno questo dispositivo" are both correct in italian. I think the better one is the second one (which is "updating this device")

**Comment by Raffaele74** [comment]
I did it in pull request "Title Statistiche"

**Comment by lagerspetz** [comment]
This is now live in our testing version. If you are not a tester yet, you can join here:
https://play.google.com/apps/testing/edu.berkeley.cs.amplab.carat.android

**Comment by Raffaele74** [comment]
It seems to me same old version. It says Carat 2.17.4
Also zero Hogs .... you sisn't have Bugs ... is same.

**Comment by lagerspetz** [comment]
Maybe you were a little too fast. It may take some time to update. It should be 2.17.5.

**Comment by lagerspetz** [comment]
I got the new version from Google Play on my device and tried it, but seems that there is one more "usualmente" in Hogs screen top description. I have fixed it, and it will be available in the next version.

**Comment by lagerspetz** [comment]
The version ( 2.17.6 ) in testing should include these changes. Please test and close this if these are good now. Thanks.

**Comment by Raffaele74** [comment]
Checked! It is very well!
@SteX986 
You can close it.
Cheers

**Comment by SteX986** [comment]
Thanks very much to everyone :)
