### ISSUE TITLE
Beta - Jscore

### ISSUE THREAD

**Issue by Raffaele74** [carat-project/carat-android#24]
I suppose thera only two relevant problem in beta. This and threshold (easy to change).

**Comment by Raffaele74** [comment]
There is a trouble. Starting my J-score is negative, after a lot is 99%. I'm happy, bt I'm not shure.
Installed on 17:30.

By the way: can Carat answer to top-day-question? Nougat vs Marsh Mallow battery drain.

I need to know who are my J-score-friends for store presentation.
Scaling:
1 - All device
2- All smartphone
3 - All Huawei
4 - All P9
5 - All P9 lite
6 - All P9 lite no barnd
7 - All P9 lite no brand single sim
8 - ...... with Android x ....

![jscore](https://user-images.githubusercontent.com/24221053/27821747-a9e89bf8-60a3-11e7-88f4-d33e30734402.png)

**Comment by lagerspetz** [comment]
JScore is now compared with devices of the same model as you have. If you are the best on your model, then your JScore will be 99. That is also true if you are the only one with your model.
However, you will not get a JScore at all if we have no data on your model yet.

**Comment by Raffaele74** [comment]
Excuse me, but I had a negative J-score. Better a control about this. Probably it happens when Hogs=0.

**Comment by lagerspetz** [comment]
the negative J-Score was a problem with the way J-Scores were calculated server-side. That has been fixed.
