### ISSUE TITLE
866%

### ISSUE THREAD

**Issue by Raffaele74** [carat-project/carat-android#36]
In statistic (users havig almost a trouble).

![img_20170705_073948](https://user-images.githubusercontent.com/24221053/27856162-74a00dc6-616d-11e7-9584-0c964541d99c.png)

**Comment by Raffaele74** [comment]
Solved today. Ok.

**Comment by lagerspetz** [comment]
Yes, this was an issue that resulted from investigating missing JScores / Hogs / Bugs for users not using the Testing version. Old non-testing version results, that included all of the data from 2012 to today, appeared on the statistics site. From now on, the statistics site should only have stats from the current year, so 2016 July to 2017 July.
