### ISSUE TITLE
Action bug

### ISSUE THREAD

**Issue by Raffaele74** [carat-project/carat-android#4]
Android 6: Carat kill command doesn't kill HOGS. Manage does it Manage needs two click, but it is shure. But every threat is also opportunity. Since the data are already reported in Bugs and Hogs you can simplify this frequently used page.

![a36c83e2-1504-11e7-8609-55f79be1a258](https://cloud.githubusercontent.com/assets/24221053/25735865/9f91a244-316e-11e7-82af-fc8339edb494.png)

**Comment by lagerspetz** [comment]
We will need to check if Killing does not work on Android 6. Thanks for the report.

**Comment by jhamberg** [comment]
This uses killBackgroundProcesses, which is the only method exposed by Android API. Its behavior has always been a bit unreliable (although killing applications that are system signed never worked). However, it's the best we got. Of course, we could consider removing the option altogether for system applications and poll the process list for normal applications to see whether they were killed or not, allowing us to guide to user if needed. I could not find any information about this method being deprecated on Android 6.0+.

**Comment by Raffaele74** [comment]
I think leaving only "Manage" + "End" eliminating the only-one-command "End" is a valid solution. I've cheked them a lot: on my device "Manage" + "End" does it really and definitely in 100% of cases. Only-one-commad "End" does not execute any command ever.
Huawei P9

**Comment by Raffaele74** [comment]
It is also in last beta build.
Brainstorming: can I change orange-kill-button with gray-kill-button in setting? In setting I can say when it doesn't work. I'm Android MM.

**Comment by lagerspetz** [comment]
Raffaele, we don't know when killing does not work, until we try it. So we cannot gray it out from the start, so users will still have this problem. I think the only solution is removing the button, but some people want to have that button, since it does work for some apps.

**Comment by Raffaele74** [comment]
If you put color of kill-buttom in settings, you can view who will change, so you have a tip to understand. 

Carat should advise with a pop up during installation, kill can work or not, and this do happy who want it and who doesn't want.

And also when kill-button doesn't work it is an help because it change from "Termina" to "Fermata"

http://www.gifmania.it/Gif-Animate-Emoticon/Immagini-Animate-Smiley-Con-Il-Messaggio/Smiley-Con-Il-Messaggio-82397.gif

**Comment by Raffaele74** [comment]
And also when kill-button doesn't work it is an help because it change from "Termina" to "Fermata"
