### ISSUE TITLE
Statistics: percentages don't sum up to 100%

### ISSUE THREAD

**Issue by Raffaele74** [carat-project/carat-android#41]
There are some little, little, little bugs.

As you rounds, sum of % may be it is not 100%.
But it is impossible thet sum of 4 item of iOS is 96% (it must be almost 97%).

In the cake you over Android and trunc iOS to do 100%. Better you round both.

In the cake you show Android+iOS, But it is not in alfanumeric (they sum 200%).
As cake is to big, I think better 3 cakes landscape. iOS vs Android - iOS - Android. Likely to view and simpler to calculate.

**Comment by lagerspetz** [comment]
We don't show fractional percentages, that's why it does not sum up to 100.
Android + iOS is good the way it is, so you can compare the fraction of Android vs iOS users visually.

**Comment by Raffaele74** [comment]
Forgive me. I do it with the spirit of testing.

If I add "n" item, incomplete sum can be sum +- n / 2 (rounding).
In iOS i have 4 addendums, so the uncompleted sum can be 98% <x <102%. Instead it is 96% (100-n).

Cake: round iOS is 56,7%, you do 56%; Android is 43,3% you do 44%.

**Comment by Raffaele74** [comment]
I noticed it, I must say it, but that's fine, I guess the problem is on small ticks.
