### ISSUE TITLE
save_accept_eula in strings

### ISSUE THREAD

**Issue by MrMargouillat** [carat-project/carat-android#51]
Hi, I think that this string might be in the wrong place... Or at least must have the untranslatable attribute.

**Comment by MrMargouillat** [comment]
TutorialActivity too?

**Comment by lagerspetz** [comment]
Oh yes, that string should definitely be translatable="false". I will fix it :)
TutorialActivity as well. That title is not displayed to the user so no need to translate.

**Comment by MrMargouillat** [comment]
"out_of" and "title_activity_tutorial" too ?

**Comment by lagerspetz** [comment]
out_of is ok here. It has the CDATA code because it needs to include spaces, since the Finnish version has no spaces. Translating is complicated :). See https://github.com/carat-project/carat-android/commit/6a5060dd44b12b804c90ba76019d20b70df14af6

**Comment by MrMargouillat** [comment]
Oki perfect ;)

**Comment by lagerspetz** [comment]
I am wondering if this actually causes https://github.com/carat-project/carat-android/issues/49

**Comment by MrMargouillat** [comment]
It looks like you were right! ;)
