### ISSUE TITLE
Out of range

### ISSUE THREAD

**Issue by Raffaele74** [carat-project/carat-android#53]
I attach the screenshoot of a user who has a very high battery consumption. Her Carat Jscore is -31%. 
It's a Huawei P10. 

Mine is 99%. I'm VNS L31.

The Carat build  is 2.17.9 (both).

![out of range](https://user-images.githubusercontent.com/24221053/32413508-af48f23e-c212-11e7-986a-815669d6add0.png)

**Comment by lagerspetz** [comment]
Hi, the negative J-Scores appeared once during development of a new analysis system, and were overwritten since. It may be that this is caused by issues in the current Carat version. I have put an update on Google Play (version 2.17.10). Does that fix it for you?

**Comment by Raffaele74** [comment]
Yes.  It is with current build.
Old build it was -31%, new build it is -30%.
It is on a device with very high battery drain.
It is P10.

![meno30](https://user-images.githubusercontent.com/24221053/32483762-a4e09162-c39d-11e7-8e8e-b54df2f69f91.png)

**Comment by Raffaele74** [comment]
Solved ! ;-)

![ok](https://user-images.githubusercontent.com/24221053/32687031-e0203ab2-c6b2-11e7-806b-7f9e5b2468bf.png)

**Comment by lagerspetz** [comment]
Good to know, thanks!
