### ISSUE TITLE
 Android warnign about Carat battery drain

### ISSUE THREAD

**Issue by Raffaele74** [carat-project/carat-android#54]
After about 10 hours (I verified over several days) Android reports a too big battery drain from Carat and proposes killing it. 
I do not know what can be done, but with charge to 100%,  Android reset the count for the warning, then reducing consumption half-way may be a solution (maybe with less background activity).

![battery drain](https://user-images.githubusercontent.com/24221053/32413560-f2a3f8b6-c213-11e7-924b-88d06fd2eb28.png)

**Comment by Raffaele74** [comment]
It may be a trouble connecting servers.
New build is very, very slow, and I received warning when I view "statistic".

**Comment by lagerspetz** [comment]
Yes, i have noticed this too. Seems to be very slow especially on mobile network. I'm investigating.On Nov 5, 2017 11:42 AM, Raffaele74 <notifications@github.com> wrote:It may be a trouble connecting servers.
New build is very, very slow, and I received warning when I view "statistic".

**Comment by Raffaele74** [comment]
I viewed in #54 that Patrizia's Carat didn't connect to servers.
Also my Tablet (Lenovo) didn't connect with last build.

**Comment by Raffaele74** [comment]
I setted "upgrade on background" on tablet and it seems better.
But it continuosly alternatively does:
> updating status (not always)
> upgrade device (long time)
> upgrade bugs (short time)
and nothing more.

**Comment by Raffaele74** [comment]
This is connections trend of my P9 lite aligned with the new version (j-score 99% as ok check). On my P9 lite app setted on *"wifi only"*.

Going to unknowed tune, looking at jpg, I suppose today 5.11.2017  Carat is trying to connect, but it is not the right day to do. The day may be tomorrow for mobile and the 8th for wifi.

![wifi e mobile](https://user-images.githubusercontent.com/24221053/32417927-d70bbdee-c260-11e7-99f5-9ef0e3338c53.png)

**Comment by lagerspetz** [comment]
Sorry about that. Everything worked on our end when we tested this version, but it seems not to work any more.
We have published a new version that should fix it for now.

**Comment by Raffaele74** [comment]
That's not a problem for me. It's just for testing. Had it been a problem (and it is not) I could disable Carat-mobile by Android. 
The purpose of the charts is to identify battery warning problem. 

I see on my device that Carat looks for connecting (rotating circle) every time I open it, but in the graphics I see it does it every about a week.

**Comment by Raffaele74** [comment]
Solved
