### ISSUE TITLE
Failed to resolve: fi.helsinki.cs.nodes.carat:carat-protocol:1.9.3

### ISSUE THREAD

**Issue by directionyu** [carat-project/carat-android#60]
hello .after import Carat project into the IDE .  Failed to resolve: fi.helsinki.cs.nodes.carat:carat-protocol:1.9.3

**Comment by lagerspetz** [comment]
Hi. Please do a git submodule init.

**Comment by lagerspetz** [comment]
I tried including this via Jitpack, but that didn't work.

**Comment by lagerspetz** [comment]
Solved by this procedure: 
```
git submodule init
git submodule update
cd carat-protocol
./gen-publish.sh
```
You need Apache Thrift compiler (v.0.11) and Java 1.8 to do this.
