### ISSUE TITLE
No J-Score?

### ISSUE THREAD

**Issue by irishatheist** [carat-project/carat-android#64]
No J-score on Moto G4 PVTB

**Comment by irishatheist** [comment]
Eventually reported j-score

**Comment by lagerspetz** [comment]
Hi, Yes, I can see the analysis was rerun last night. Good that you have a score now. --Eemil LagerspetzOn 8 Jun 2019 07:50, irishatheist <notifications@github.com> wrote:














Eventually reported j-score
