### ISSUE TITLE
Unable to build the carat-android project.

### ISSUE THREAD

**Issue by kofboy2000** [carat-project/carat-android#66]
Whenever I'm trying to build the carat-android, latest at master branch, the build is failed with below log.

ERROR: Failed to resolve: fi.helsinki.cs.nodes.carat:carat-protocol:1.9.3
Show in Project Structure dialog
Affected Modules: caratApp

I also tried to modify the build.gralde as below.

//implementation 'fi.helsinki.cs.nodes.carat:carat-protocol:1.9.3' exclude group: 'org.slf4j'
implementation 'com.github.carat-project:carat-protocol:1.9.3' exclude group: 'org.slf4j'

After that, the build error occurred from java code. :(
Is there anything I should do to build the project?

Thank you for the help in advance. :)

**Comment by lagerspetz** [comment]
We have the carat-protocol project as a submodule.You need to init
submodules and then build it.
-- 
On Tue, 2020-04-21 at 22:42 -0700, Taieui Song wrote:
> 
> 
> 
> 
> [data-x-cs-warn] { position: relative; }
> [data-x-cs-warn]:hover:after {
>   position: absolute;
>   top: -7px;
>   left: 50px;
>   width: 480px;
>   content: attr(data-x-cs-warn);
>   background-color: #ffffff; color: #ff0044; font-size: 8pt; font-
> family: Arial, sans-serif; font-weight: bold; line-height: 12px;
> float: left; text-align: left; margin-left: 10px; margin-right: 10px;
> border: 2px dotted #ff0044; padding: 5px;
> }
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> Whenever I'm trying to build the carat-android, latest at master
> branch, the build is failed with below log.
> ERROR: Failed to resolve: fi.helsinki.cs.nodes.carat:carat-
> protocol:1.9.3
> 
> Show in Project Structure dialog
> 
> Affected Modules: caratApp
> I also tried to modify the build.gralde as below.
> //implementation 'fi.helsinki.cs.nodes.carat:carat-protocol:1.9.3'
> exclude group: 'org.slf4j'
> 
> implementation 'com.github.carat-project:carat-protocol:1.9.3'
> exclude group: 'org.slf4j'
> After that, the build error occurred from java code. :(
> 
> Is there anything I should do to build the project?
> Thank you for the help in advance. :)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 
Dr. Eemil Lagerspetz
Docent, Postdoctoral Researcher
Department of Computer Science
PO Box 68, FI-00014 University of Helsinki, Finland
email: eemil@gmx.com or eemil.lagerspetz@cs.helsinki.fi
web: www.cs.helsinki.fi/u/lagerspe/

**Comment by kofboy2000** [comment]
Thank you for the guide.

The build succeed by
- build carat-protocol and generate carat-protocol-1.9.3.jar.
- copy the jar file under caratApp libs folder.
- modify build.gradle of caratApp by 
  //implementation 'fi.helsinki.cs.nodes.carat:carat-protocol:1.9.3' exclude group: 'org.slf4j'
  implementation 'com.github.carat-project:carat-protocol:1.9.3' exclude group: 'org.slf4j'

I hope I did all correct way. :-)

Thank you!

**Comment by lagerspetz** [comment]
Hi, That should work. Another way is to "publish" the carat protocol to the local maven/gradle repository, that should not need the rename.Best,Docent, Dr. Eemil LagerspetzDepartment of Computer Science University of Helsinki23.4.2020 7.23 Taieui Song <notifications@github.com> kirjoitti:















Thank you for the guide.
The build succeed by
build carat-protocol and generate carat-protocol-1.9.3.jar.copy the jar file under caratApp libs folder.modify build.gradle of caratApp by
//implementation 'fi.helsinki.cs.nodes.carat:carat-protocol:1.9.3' exclude group: 'org.slf4j'
implementation 'com.github.carat-project:carat-protocol:1.9.3' exclude group: 'org.slf4j'
I hope I did all correct way. :-)
Thank you!

**Comment by kofboy2000** [comment]
Thank you for your guide!
Have a wonderful day!
